name: PeriodicTable
description: Flutter Periodic Table App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  simple_animations: ^2.2.1
  bloc: ^5.0.1
  flutter_bloc: ^5.0.1
  meta: ^1.1.8
  flare_flutter: ^2.0.5
  flutter_speed_dial: ^1.2.5


  # The following adds the Cupertino Icons font pluto your application.
  # Use with the CupertinoIcons class for iOS style icons.\
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  # flutter_test:
  #   sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path: "assets/launcher/app_logo_flutter.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
    # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Nav.flr
    - assets/pTable.json 

module:
  androidX: true
